audatex:
  taskServiceWsdl: https://www-a.audatex.net/b2b/services/TaskService_v1?wsdl
  attachmentServiceWsdl: https://www-a.audatex.net/b2b/services/AttachmentService_v1?wsdl
  debugWsMessages: true
  responsibleOrganizationId: MM-O-69289C2F

server:
  port: 8088

logging:
  level:
    root: INFO
    org:
      apache: ERROR
      springframework: ERROR
    pl:
      coderion: INFO
