
package com.audatex.b2b.serviceinterface_v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-05T21:07:32.496+01:00
 * Generated source version: 3.1.9
 * 
 */
public final class AttachmentServicePort_AttachmentServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://serviceinterface_v1.b2b.audatex.com", "AttachmentService");

    private AttachmentServicePort_AttachmentServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AttachmentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AttachmentService ss = new AttachmentService(wsdlURL, SERVICE_NAME);
        AttachmentServicePort port = ss.getAttachmentServicePort();  
        
        {
        System.out.println("Invoking getAttachmentsContent...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _getAttachmentsContent_getAttachmentsContentRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _getAttachmentsContent__return = port.getAttachmentsContent(_getAttachmentsContent_getAttachmentsContentRequest);
        System.out.println("getAttachmentsContent.result=" + _getAttachmentsContent__return);


        }
        {
        System.out.println("Invoking ping...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _ping_pingRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _ping__return = port.ping(_ping_pingRequest);
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking addAttachmentsToTask...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _addAttachmentsToTask_addAttachmentsToTaskRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _addAttachmentsToTask__return = port.addAttachmentsToTask(_addAttachmentsToTask_addAttachmentsToTaskRequest);
        System.out.println("addAttachmentsToTask.result=" + _addAttachmentsToTask__return);


        }
        {
        System.out.println("Invoking executeAction...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _executeAction_executeActionRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _executeAction__return = port.executeAction(_executeAction_executeActionRequest);
        System.out.println("executeAction.result=" + _executeAction__return);


        }
        {
        System.out.println("Invoking deleteNonGlobalAttachments...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _deleteNonGlobalAttachments_deleteNonGlobalAttachmentsRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _deleteNonGlobalAttachments__return = port.deleteNonGlobalAttachments(_deleteNonGlobalAttachments_deleteNonGlobalAttachmentsRequest);
        System.out.println("deleteNonGlobalAttachments.result=" + _deleteNonGlobalAttachments__return);


        }
        {
        System.out.println("Invoking deleteAttachments...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _deleteAttachments_deleteAttachmentsRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _deleteAttachments__return = port.deleteAttachments(_deleteAttachments_deleteAttachmentsRequest);
        System.out.println("deleteAttachments.result=" + _deleteAttachments__return);


        }
        {
        System.out.println("Invoking addAttachmentsToTaskCalculation...");
        com.audatex.b2b.serviceinterface_v1.B2BRequest _addAttachmentsToTaskCalculation_addAttachmentsToTaskCalculationRequest = new com.audatex.b2b.serviceinterface_v1.B2BRequest();
        com.audatex.b2b.serviceinterface_v1.B2BResponse _addAttachmentsToTaskCalculation__return = port.addAttachmentsToTaskCalculation(_addAttachmentsToTaskCalculation_addAttachmentsToTaskCalculationRequest);
        System.out.println("addAttachmentsToTaskCalculation.result=" + _addAttachmentsToTaskCalculation__return);


        }

        System.exit(0);
    }

}
